when:
  - event: manual

steps:
  - name: decrypt
    image: alpine:latest
    environment:
      SECRET_KEY:
        from_secret: SECRET_KEY
    commands:
      - apk add --no-cache openssl make bash
      - make dec-wpsecrets

  - name: deploy
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker compose build nginx #todo: doesnt have to build everytime only if change affects the image inside it needs to build
      - docker compose up -d
      - docker exec nginx nginx -s reload